---
title: "SOC 232 GSS Analytics"
author: "Zachary Finacchio"
format:
  html:
    embed-resources: true
toc: true
execute:
  echo: false
  warning: false
  message: false
---

```{r packages}
library(tidyverse)
library(here)
library(readxl)
library(forcats)
```

```{r html-setup}
# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 9, # 7" width
  fig.asp = 0.666, # the golden ratio
  fig.retina = 3, # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300 # higher dpi, sharper image
)
```

```{r load-data}
GSS <- read_excel(here::here("data/GSS.xlsx"), range = "A1:K3545",
                     col_names = TRUE)
```

```{r data-cleaning}
GSS <- GSS |>
  filter(age < 36,
         age != ".n:  No answer") |>
  mutate(partners = if_else(partners == ".i:  Inapplicable" | partners == "No partners",
                            "0", as.character(partners)),
         partners = if_else(partners == ".d:  Do not Know/Cannot Choose",
                            "11-20 partners", as.character(partners)),
         nummen = if_else(nummen == ".i:  Inapplicable", "0", as.character(nummen)),
         nummen = if_else(nummen == ".n:  No answer", NA, as.character(nummen)),	
         numwomen = if_else(numwomen == ".i:  Inapplicable", "0", as.character(numwomen)),
         numwomen = if_else(numwomen == ".n:  No answer", NA, as.character(numwomen)),
         fear = case_when(fear == "YES" | fear == "NO" ~ fear,
                          .default = NA),
         matesex = if_else(matesex == ".i:  Inapplicable", "NO", matesex)
         ) 
```

```{r data-category-cleaning}
myGSS <- GSS |>
  mutate(sexornt = case_when(sexornt == "Heterosexual or straight" ~ "Heterosexual",
                             sexornt == "Gay, lesbian, or homosexual" |
                               sexornt == ".d:  Do not Know/Cannot Choose" |
                               sexornt == "Bisexual" ~ "Queer"),
         lifepartners = as.double(nummen) + as.double(numwomen)
         )
         
```

```{r}
myGSS <- myGSS |>
  mutate(combos = case_when(sexornt == "Queer" & sex == "MALE" ~ "Queer Men",
                            sexornt == "Queer" & sex == "FEMALE" ~ "Queer Women",
                            sexornt == "Heterosexual" & sex == "MALE" ~ "Heterosexual Men",
                            sexornt == "Heterosexual" & sex == "FEMALE" ~ "Heterosexual Women"))
```


```{r lifepartners-data}
mean_partners_data <- 
  myGSS |>
  na.omit(sexornt) |>
  group_by(sexornt, sex)|>
  mutate(mean_part = mean(lifepartners)) |>
  mutate(sd = sd(lifepartners)) |>
  count(combos, mean_part, sd) |>
  mutate(se = sd/sqrt(n))
```

```{r lifepartners-plor}
ggplot(data = mean_partners_data, aes(y = mean_part, x = sexornt, fill = sex)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(mean_part, 3), y = mean_part + 0.5, x = c(0.77, 1.225, 1.77, 2.225), position = sex)) +
 # geom_errorbar(aes(ymin = mean_part - se, ymax = mean_part + se)) +
  labs(y = "Mean Number of Lifetime Sexual Partners",
       x = "Sexual Orientation",
       fill = "Sex") +
  scale_fill_manual(values = c("pink", "blue")) +
  theme_classic()
```

```{r fear-manipulation}
fear_prop_data <- myGSS |>
  na.omit(sexornt) |>
  group_by(sex, sexornt, combos) |>
  count(fear) |>
  mutate(prop = n/sum(n)) |>
  mutate(sd = sd(prop))
```

```{r fear-data}
fear_prop_data <- 
  myGSS |>
  na.omit(sexornt) |>
  group_by(sexornt, sex, combos)|>
  count(fear) |>
  mutate(prop = n/sum(n))  |>
  mutate(sd = sd(prop)) |>
  mutate(se = sd/sqrt(sum(n))) |>
  filter(fear == "YES")# |>
 # fct_relevel(as.character(combos), levels = c("Heterosexual Women", "Heterosexual Men", "Queer Women", "Queer Men"))


fear_prop_data
```

```{r fear-plot}
ggplot(data = fear_prop_data, aes(y = prop, x = sexornt, fill = sex)) +
  geom_col(position = "dodge") +
    labs(y = "Percentage Afraid to Walk Alone at Night",
       x = "Sexual Orientation",
       fill = "Sex") +
  geom_text(aes(label = round(prop, 3), y = prop + 0.02, x = c(0.775, 1.225, 1.775, 2.225), position = sex)) +
  scale_fill_manual(values = c("pink", "blue")) + 
  theme_classic() # +
 # geom_errorbar(aes(ymin = prop - sd, ymax = prop + sd))
```

